<div class="widget">
            <h2> <a href="$movie.link$"> $movie.title$ </a>  </h2>
            <div class="photo">
                    <a href="$movie.link$">
                        <img
                            src="$movie.imageLink$"
                            title="$movie.title$"
                            class="aligncenter"
                            width="$movie.imageWidth$"
                            height="$movie.imageHeight$"
                            alt="$movie.title$"/>
                    </a>
                    
                    <div class="regular">
                        $movie.description$
                        <br>
                        <b>Rating&nbsp;</b> $movie.rating$

                </div>
                <br style="clear:both"/>
            </div> <!-- photo -->

</div>
