<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head><title> $siteName$ - $pageName$  </title>

<link rel="stylesheet" href="http://www.moviebook.info/art/common/yui/reset-fonts-grids.css" type="text/css">
<link rel="stylesheet" href="http://www.moviebook.info/art/minimal/main.css" type="text/css">
<link rel="stylesheet" href="http://www.moviebook.info/art/minimal/menu/vertical.css" type="text/css">

    <!--[if lt IE 8]>
        <style type="text/css">  .widget .photo img { width:100% ; max-width: 100% ; }   </style>
    <![endif]-->

    </head>

 <body>

<div id="top-toolbar">

</div> <!-- top toolbar -->

<div id="custom-doc" class="yui-t2">

<div id="hd" role="banner">

<div class="block">
		 <div id="round-banner">
			<h1><a href="#"> $siteName$ </a></h1>
			<div class="description"> $pageName$ </div>
		</div>
</div>

</div> <!-- hd block -->

 <div id="bd" role="main">
	<div id="yui-main">
        <div class="yui-b">
            $pageContent$
        </div>
    </div> <!-- yui-main -->
	<div class="yui-b">
         Menus
    </div>

</div> <!-- yui-bd -->


</div> <!-- custom-doc -->

<div id="ft" role="contentinfo">
        <p class="copyright">
        &copy; All Rights Reserved &nbsp; $siteName$
        
    </p>
</div><!-- footer -->


</body>

</html>
