<div class="widget">
            <h2> <a href="$photo.link$"> $photo.title$ </a>  </h2>
            <div class="photo">
                    <img src="$photo.imageLink$"  title="$photo.title$"  class="aligncenter" alt="$photo.title$"/>
                <div class="regular">
                    $photo.description$
                </div>
                <br style="clear:both"/>
            </div> <!-- photo -->

</div>
