        <div class="video">
            <div class="$alignment$">

                   <object width="320" height="240">
                    <param name="movie" value="http://www.youtube.com/v/$videoId$&amp;hl=en_US&amp;fs=1?rel=0&amp;border=1"></param>
                    <param name="allowFullScreen" value="true"></param>
                    <param name="allowscriptaccess" value="always"></param>
                        <embed src="http://www.youtube.com/v/$videoId$&amp;hl=en_US&amp;fs=1?rel=0&amp;border=1"
                            type="application/x-shockwave-flash"
                            allowscriptaccess="always"
                            allowfullscreen="true"
                            width="320"
                            height="240">
                        </embed>
                    </object>

                </div>
                <div class="regular" style="margin:10px;"> $description$ </div>
                <br style="clear:both"/>

        </div>



