<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head><title> $siteName$ - $pageName$  </title>

<meta name="keywords" content="$pageName$,movie based on books" />

<link rel="stylesheet" href="http://www.moviebook.info/art/common/yui/reset-fonts-grids.css" type="text/css">
<link rel="stylesheet" href="http://www.moviebook.info/art/black/main.css" type="text/css">
<link rel="stylesheet" href="http://www.moviebook.info/art/black/menu/vertical.css" type="text/css">

    <!--[if lt IE 8]>
        <style type="text/css">  .widget .photo img { width:100% ; max-width: 100% ; }   </style>
    <![endif]-->

   <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17886288-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

    </head>

 <body>

<div id="top-toolbar">

</div> <!-- top toolbar -->

<div id="custom-doc" class="yui-t2">

<div id="hd" role="banner">

<div class="block">
		 <div id="round-banner">
			<h1><a href="#"> $siteName$ </a></h1>
			<div class="description"> $pageName$ </div>
		</div>
</div>

</div> <!-- hd block -->

 <div id="bd" role="main">
	<div id="yui-main">
        <div class="yui-b">
            $pageContent$
        </div>
    </div> <!-- yui-main -->
	<div class="yui-b">
        $menuHtml$
    </div>

</div> <!-- yui-bd -->


</div> <!-- custom-doc -->

<div id="ft" role="contentinfo">
        <p class="copyright">
        &copy; All Rights Reserved &nbsp; $siteName$
        
    </p>
</div><!-- footer -->


</body>

</html>
