<div class="widget">
            <h2> <a href="$photo.link$"> $photo.title$ </a>  </h2>
            <div class="photo">
                    <a href="$photo.link$">
                        <img
                            src="$photo.imageLink$"
                            title="$photo.title$"
                            class="$photo.alignment$"
                            width="$photo.width$"
                            height="$photo.height$"
                            alt="$photo.title$"/>
                    </a>
                    
                    <div class="regular">
                        $photo.description$
                      
                </div>
                <br style="clear:both"/>
            </div> <!-- photo -->

</div>
